using BerriedDelight.Models;

namespace BerriedDelight.Models
{
    public static class DbInitializer
    {
        public static void Seed(IApplicationBuilder applicationBuilder)
        {
            BerriedDelightDbContext context =
                applicationBuilder.ApplicationServices.CreateScope().
                ServiceProvider.GetRequiredService<BerriedDelightDbContext>();

            if (!context.Categories.Any())
            {
                context.Categories.AddRange(Categories.Select(c => c.Value));
            }

            if (!context.Berries.Any())
            {
                context.AddRange
                (
                    //DESCRIPTIONS GENERATED BY CHATGPT 3.5
                    //Berries list
                    new Berry { Name = "Strawberries", Price = 4.95M, Description = "Strawberries are a delicious and versatile fruit known for their bright red color, juicy texture, and sweet flavor. They are rich in vitamin C, antioxidants, and fiber, making them a healthy choice for snacks, desserts, and salads. Strawberries can be enjoyed fresh, sliced, or whole, and they are also popular in jams, sauces, and baked goods. Their vibrant appearance and refreshing taste make them a favorite fruit for many people around the world.", Category = Categories["Summer Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/strawberries.jpg", RecommendedRecipie = "Placeholder", InStock = true, IsPopularBerry = true, ImageThumbnailUrl = "Images/strawberriessmall.jpg" },
                    new Berry { Name = "Blueberries", Price = 6.55M, Description = "Blueberries are small, round berries with a deep blue color and a sweet yet slightly acidic flavor. They are packed with antioxidants, vitamins, and minerals, making them a nutritious addition to any diet. Blueberries can be enjoyed fresh or frozen and are often used in a variety of dishes, including muffins, pancakes, smoothies, and salads. Their vibrant color and delicious taste make them a popular choice for both sweet and savory recipes.", Category = Categories["Spring Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/blueberries.jpg", RecommendedRecipie = "Placeholder", InStock = true, IsPopularBerry = true, ImageThumbnailUrl = "Images/blueberriessmall.jpg" },
                    new Berry { Name = "Cranberries", Price = 5.45M, Description = "Cranberries are tart, red berries that grow on evergreen shrubs in wet areas. They are known for their bright color and tangy flavor, which adds a unique zing to dishes. Cranberries are rich in antioxidants and are often consumed in juice form to promote urinary tract health. They are also used in sauces, relishes, and baked goods, especially during the holiday season. Despite their tartness, cranberries can be a delicious and nutritious addition to your diet.", Category = Categories["Winter Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/cranberries.jpg", RecommendedRecipie = "Placeholder", InStock = false, IsPopularBerry = true, ImageThumbnailUrl = "Images/cranberriessmall.jpg" },
                    new Berry { Name = "Elderberries", Price = 6.00M, Description = "Elderberries are the dark purple fruit of the elder tree, known for their rich, tart flavor and numerous health benefits. These small berries are often used in culinary creations such as jams, jellies, syrups, and baked goods, as well as in beverages like elderberry wine and tea. Elderberries are also praised for their potential immune-boosting properties and are a popular natural remedy for colds and flu. Rich in antioxidants and vitamins, elderberries are a versatile and nutritious addition to a balanced diet.", Category = Categories["Autumn Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/elderberries.jpg", RecommendedRecipie = "Placeholder", InStock = true, IsPopularBerry = false, ImageThumbnailUrl = "Images/elderberriessmall.jpg" },
                    new Berry { Name = "Raspberries", Price = 7.50M, Description = "Raspberries are small, delicate berries with a sweet yet slightly tart flavor. They are known for their vibrant red color and soft, juicy texture. Raspberries are rich in antioxidants, fiber, and vitamins, making them a nutritious addition to your diet. These berries are often enjoyed fresh, but they can also be used in a variety of dishes, including jams, sauces, desserts, and baked goods. Their distinctive flavor and bright appearance make them a popular choice for both sweet and savory recipes.", Category = Categories["Summer Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/raspberries.jpg", RecommendedRecipie = "Placeholder", InStock = true, IsPopularBerry = false, ImageThumbnailUrl = "Images/raspberriessmall.jpg" },
                    new Berry { Name = "Gooseberries", Price = 8.00M, Description = "Gooseberries are small, round berries with a slightly tart flavor and a greenish to reddish color. They are known for their unique taste, which is a combination of sweet and sour notes. Gooseberries are rich in vitamins, minerals, and antioxidants; these berries can be enjoyed fresh or used in a variety of dishes, including pies, jams, sauces, and desserts. Their distinct flavor and vibrant color make them a versatile and delicious fruit option.", Category = Categories["Spring Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/gooseberries.jpg", RecommendedRecipie = "Placeholder", InStock = false, IsPopularBerry = false, ImageThumbnailUrl = "Images/gooseberriessmall.jpg" },
                    new Berry { Name = "Lingonberries", Price = 22.00M, Description = "Lingonberries are small, round berries that grow on low, evergreen shrubs in cold, northern regions. They are known for their bright red color and tart, slightly acidic flavor. Lingonberries are rich in antioxidants, vitamins, and minerals. They are often enjoyed fresh or used in a variety of dishes, including jams, sauces, and desserts.", Category = Categories["Winter Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/lingonberries.jpg", RecommendedRecipie = "Placeholder", InStock = true, IsPopularBerry = false, ImageThumbnailUrl = "Images/lingonberriessmall.jpg" },
                    new Berry { Name = "Rowanberries", Price = 18.25M, Description = "Rowanberries, also known as mountain ash berries, are small, round berries that grow on the rowan tree, which is native to temperate regions of the Northern Hemisphere. These berries are known for their vibrant red-orange color and tart flavor. Rowanberries are rich in vitamin C, antioxidants, and fiber.", Category = Categories["Autumn Berries"], ImageUrl = "D:/Parth's Drive/WelTec/IT level 7/SD7501/SD7501 Assignments/BerriedDelight/BerriedDelight/wwwroot/Images/rowanberries.jpg", RecommendedRecipie = "Placeholder", InStock = false, IsPopularBerry = false, ImageThumbnailUrl = "Images/rowanberriessmall.jpg" }
                );
            }

            context.SaveChanges();
        }

        private static Dictionary<string, Category>? categories;

        public static Dictionary<string, Category> Categories
        {
            get
            {
                //Categories list
                if (categories == null)
                {
                    var genresList = new Category[]
                    {
                        new Category { CategoryName = "Summer Berries" },
                        new Category { CategoryName = "Autumn Berries" },
                        new Category { CategoryName = "Winter Berries" },
                        new Category { CategoryName = "Spring Berries" }
                    };

                    categories = new Dictionary<string, Category>();

                    foreach (Category genre in genresList)
                    {
                        categories.Add(genre.CategoryName, genre);
                    }
                }

                return categories;
            }
        }
    }
}
